### ISSUE TITLE
Install with Cocoapod !

### ISSUE THREAD

**Issue by wonder2011** [atrbx5/PdfBuilder#3]
Please can u make a pod from this, to user's be able to install with cocoa pod ?

**Comment by atrbx5** [comment]
I will do it soon, did you face any problems with SPM?

**Comment by wonder2011** [comment]
@atrbx5 I don't use SPM. This library is awesome so support for Cocoa Pod is needed.

**Comment by wonder2011** [comment]
@atrbx5 please reflect how to install with cocoa pod in the readme !
